### ISSUE TITLE
NameError: name 'nori' is not defined

### ISSUE THREAD

**Issue by xmlyqing00** [megvii-research/OMNet#8]
Hi,

Nice work. I followed your instructions and set up the environment. I got this error when I try to test your pretrained model. Is `Nori`  a package?

```
Traceback (most recent call last):
  File "/Ship03/Sources/PointCloud/OMNet/evaluate.py", line 174, in <module>
    dataloaders = data_loader.fetch_dataloader(params)
  File "/Ship03/Sources/PointCloud/OMNet/dataset/data_loader.py", line 172, in fetch_dataloader
    train_ds = ModelNetNpy(dataset_path,
  File "/Ship03/Sources/PointCloud/OMNet/dataset/data_loader.py", line 29, in __init__
    self._fetcher = nori.Fetcher()
NameError: name 'nori' is not defined
```

**Comment by hxwork** [comment]
Hi,

Thanks for your interest. `nori` is not required in this repo, and feel free to remove it. I will update `data_loader.py`.

Hao

**Comment by xmlyqing00** [comment]
Thanks. It works.

Now I meet the following problem that 
```
Traceback (most recent call last):
  File "/Ship03/Sources/PointCloud/OMNet/evaluate.py", line 174, in <module>
    dataloaders = data_loader.fetch_dataloader(params)
  File "/Ship03/Sources/PointCloud/OMNet/dataset/data_loader.py", line 171, in fetch_dataloader
    train_ds = ModelNetNpy(dataset_path,
  File "/Ship03/Sources/PointCloud/OMNet/dataset/data_loader.py", line 42, in __init__
    with open(os.path.join(dataset_path, "shape_names.txt")) as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/data/code/meg_brain_mine/dataset/data/modelnet_ts/shape_names.txt'
```
It seems that we should change the absolute path to a relative path.

**Comment by hxwork** [comment]
Hi,

I have solved this problem, and please check the updated code or you can fix this by yourself. :)

Hao
